name: Publish pull request branch site to GitHub Pages

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  publish-to-gh-pages:
    name: Publish site to `pr/${{ github.event.pull_request.number }}` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: pr/${{ github.event.pull_request.number }}

  comment-on-pr:
    name: Comment on pull request with link to site
    runs-on: ubuntu-latest
    needs: publish-to-gh-pages
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Comment on pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Preview site: https://metamask.github.io/snaps-simulator/pr/${context.issue.number}/`,
            });
