name: Publish pull request branch site to GitHub Pages

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  publish-to-gh-pages:
    name: Publish site to `staging` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: pr/${{ github.event.pull_request.number }}
